style: 바텀 업 모달 퍼블리싱 및 상세 페이지 정보 수정
URECA-T5/pawong pull request #24
Opened 2024-10-29 07:31 UTC by chodonghee-hub

![bottomUp_modal](https://github.com/user-attachments/assets/e802adce-65c8-4e00-9e40-524b6807e9e7)

2024-10-29 07:54 UTC, heeeione requested changes

2024-10-29 07:54 UTC, heeeione commented on src/components/donation/ItemCount.jsx
> +  };
실행문이 하나면 중괄호 빼는 게 더 좋을 것 같아요.
if (cnt.current > 0) cnt.current -=1; 이런 식으로요.

조건을 보니까 id가 btn_miuns이고 현재 cnt가 0보다 크면 -1를 하는 거라면 if문을 2개 작성하는 것보다는 && 연산자를 사용하는 게 더 좋아 보입니다.

그리고 삼항 연산자를 사용하는 건 어떤 가요?
cnt.current += e.target.id === 'btn__minus' && cnt.current > 0 ? -1 : 1;
setTotalPrice(cnt.current * price);

아마 이 코드로 될 것 같긴 한데 한 번 체크해주세요

2024-10-29 07:59 UTC, gwagjiug commented on src/style/donation/itemDetail.js
>      height: 25px;
`width` 나 `height` 단위 rem으로 변경해주세요~ border-radius 제외하고는 `rem` 을 사용하는 것이 코드 안정성이 더 높기때문입니다

2024-10-29 08:17 UTC, gwagjiug requested changes
전반적으로 스타일 컴포넌트를 좀 더 분리해서 사용하면 가독성을 높일 수 있을 것 같습니다. 

추가적으로 스타일 코드를 작성할 때 `px` 단위 사용은 지양 해주시고 `%` 나 `rem` 단위를 사용해주시는 것이 `일관성` `유지보수` `반응형` 에 장점을 가질 수 있으니 수정 부탁드립니다!~

2024-10-29 08:17 UTC, gwagjiug commented on src/style/donation/itemDetail.js
>      height: 25px;
전체적으로 스타일 단위는 `rem` 혹은 `%`으로 통일해주세요~

2024-10-29 08:17 UTC, gwagjiug commented on src/components/donation/ItemCount.jsx
> +    <BottomModalContainer
`BottomModalContainer` 에 많은 스타일이 포함되어 있는 것 같아요. 스타일 컴포넌트를 여러 개의 하위 컴포넌트로 분리해서 좀 더 명확히 하면 가독성이 좋아질 것 같습니다

2024-10-29 08:17 UTC, gwagjiug commented on src/components/donation/ImageSlide.jsx
> +            <img key={index + src} src={src} alt="" className="image__item" />
alt 속성이 빠져있네요 !

2024-10-29 16:08 UTC, heeeione approved these changes
고생하셨어요

2024-10-30 00:34 UTC, gwagjiug approved these changes
훨씬 깔끔해졌네요 수고하셨어요👍👍

2024-10-30 00:34 UTC, gwagjiug commented on src/components/donation/ItemBottomModal.jsx
> +
깔끔👍

2024-10-30 00:35 UTC, merged