임시보호 일지 퍼블리싱 및 기능 추가 완료
URECA-T5/pawong pull request #29
Opened 2024-10-30 05:25 UTC by ummfieg

**추가 및 수정사항**
- [ ] px -> rem으로 변경

- [ ] dialog 기능 추가

- [ ] 이미지 업로드 기능 추가

- [ ] 파일 이름 수정 및 변경
- components -> pages 파일로 dialog 파일 이동
-  style폴더 내 register 폴더명 careDiary로 변경

**구현 화면**

* 제목 부분을 필수 입력으로 지정해서 스타일링 했는데 의견주세요!
![일지 구현화면](https://github.com/user-attachments/assets/27310801-0b53-4426-bb7a-c07c0f5a5d93)

2024-10-30 06:14 UTC, ummfieg commented
- [ ] 태그 종류 수정 및 모달 -> 버튼으로 수정
- [ ] input태그 클릭시 테투리 포인트 컬러로 수정
- [ ] 제목 필수 입력 (제목에 * 표시) UI 변경

수정하고 다시 올릴게요!

2024-10-31 01:44 UTC, gwagjiug requested changes
그리고 추가적으로 `Modal` 위치 중앙정렬이 되었는지 궁금합니다~ 변경 사항 관련해서는 리뷰 남겼으니 `변경 가능` 하시다면 반영 부탁드립니다~

2024-10-31 01:44 UTC, gwagjiug commented on src/pages/CareDiary/CareDiary.jsx
> +  const onCancleClick = (e) => {
이 부분 함수에 오타 있습니다 ! `Cancle` => `Cancel` 확인 부탁드립니다!

2024-10-31 01:44 UTC, gwagjiug commented on src/pages/CareDiary/CareDiary.jsx
> +  };
그리고 이 함수에서 `setFormData`를 여러 번 호출하기보다는 `formData` 전체를 초기화하는 방식으로 호출을 줄이는 것은 어떤가요 ??

예를 들면 
```
  setFormData({
    tag: '',
    title: '',
    location: '',
    story: '',
    image: '',
  });
  ```
  
  이런식으로 수정할 수 있을 것 같은데 어떻게 생각하시나요?

2024-10-31 01:44 UTC, gwagjiug commented on src/pages/CareDiary/CareDiary.jsx
> +                disabled={!formData.title}
저희 등록 버튼 활성화가 `title` 만 검사하면 되는 건가요? 다른 `태그`나 `내용` 같은 필드도 필수 필드라면 그 부분도 추가해야 할 것 같은데 이유가 있었나요??

2024-10-31 01:54 UTC, ummfieg commented on src/pages/CareDiary/CareDiary.jsx
> +                disabled={!formData.title}
이 부분은 디테일 하게 논의된 부분은 없어서 제목만 우선 필수라고 넣어둔 상태에요!
그리고 피드형태로 생각하면 태그, 사진도 필수필드로 지정해야하나 싶기도합니다.
장소 제외하고 모두 필수로 넣을까요? 아니면 태그랑 내용정도 필수로 추가할까요?

2024-10-31 01:55 UTC, ummfieg commented on src/pages/CareDiary/CareDiary.jsx
> +  };
동의합니다 수정할게요!!

2024-10-31 01:55 UTC, ummfieg commented on src/pages/CareDiary/CareDiary.jsx
> +  const onCancleClick = (e) => {
오 확인했어요! 수정할게요!

2024-10-31 02:12 UTC, gwagjiug commented on src/pages/CareDiary/CareDiary.jsx
> +                disabled={!formData.title}
금방 수정이 가능한 부분이니깐 추후에 얘기해보고 수정하면 될 것 같습니다 ㅎㅎ

2024-10-31 05:29 UTC, gwagjiug approved these changes

2024-10-31 05:43 UTC, merged